kind: Route
apiVersion: route.openshift.io/v1
metadata:
  namespace: {{ocp-namespace}}
  name: orchestraror-route
  labels:
    app: orchestraror
spec:
  to:
    kind: Service
    name: orchestraror-service
    weight: 256
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
---
